### PR TITLE
fix: playground improvements for keyboard usage

### LINKED ISSUE #839: Playground improvements for keyboard usage
When I click on a playground I'm landing to a page

1. The prompt is at the bottom but is not focused so if I try to type something, nothing happens (I expect to have the blinking cursor)
1. If I use `ENTER` key after typing something, it adds a newline ? But usually on chat app, it's sending the message right away. (For a newline I use most of the time `MAJ` + `ENTER` key

I still have an issue with the prompt being collapsed to the left side and using the same color than the left navbar and not being like detached

currently it is like:
image

I expect to see something like:

image

or even more like chat apps where we have the 'send message' icon like

image

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #839

### What does this PR do?

Gives focus to the prompt and handle Enter key

### Screenshot / video of UI

playground_enter

### What issues does this PR fix or reference?

#839 

### How to test this PR?

1. Create a playground
2. Enter text + enter => should send the request

### CODE REVIEW

**Comment by benoitf** [comment]
to me it fixes the keyboard issue but the layout is still not the expected one

I expect the button being part of the widget and being centered and not attached to the left

image

**Comment by benoitf** [comment]
on my side the prompt is the same color than the background

image

**Review by lstocchi — COMMENTED** [review]
In my case, when i click Enter, the message is sent correctly but then there is an active new line in the textarea that prevents the plaholder to be seen.

**Comment by lstocchi** [comment]
@benoitf Jeff asked me to fix this as he's on PTO. If it looks good for you we can merge

**Comment by lstocchi** [comment]
> In my case, when i click Enter, the message is sent correctly but then there is an active new line in the textarea that prevents the plaholder to be seen.

fixed

**Comment by benoitf** [comment]
@lstocchi yes, probably need to update the screenshot/gif of the PR body

**Comment by lstocchi** [comment]
@benoitf updated
Sorry, i always forgot 😵‍💫

**Pull request merged**
