### PR TITLE
chore(test): add code gen test

### PR DESCRIPTION
**Pull request by cbr7**
### What does this PR do?
Adds ai lab code generation e2e smoke test

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop-extension-ai-lab/issues/1871

### CODE REVIEW

**Comment by axel7083** [comment]
50 commits ? missing some rebase ?

**Comment by cbr7** [comment]
The commits will get squashed upon merge.

**Comment by odockal** [comment]
> 50 commits ? missing some rebase ?

@cbr7 I think that @axel7083 meant that this branch is not synced with main. So rebase would be nice.

**Comment by cbr7** [comment]
It was only slightly behind main, I was keeping it updated, anyway it's synced now.

**Review by odockal — CHANGES_REQUESTED** [review]
@cbr7 please take a look at pr check error: `Error while cleaning up service models: TypeError: Cannot read properties of undefined (reading 'navigationBar')`

Otherwise I think we are good with PR. We need to make sure we can run it on CI.
Also, we need to make sure to keep actual workflows running without problems, like pr check.

**Comment by cbr7** [comment]
@odockal that error is written from try-catching an error, it's fine for it to be there, it happens when the framework tries to execute the afterAll hook after skipping all the tests since this is on Linux. There is no issue with it.

**Comment by odockal** [comment]
@cbr7 I have rerun the job and now it is ok. Strange! Anyway, these tests are not run on PR check and Nightly on Linux, so they do not block anything. And we need to figure out to make them run on windows.. or Mac?

**Comment by odockal** [comment]
@cbr7 I would be for merging and creating follow up issue to make them stable on both Windows and Mac. wdyt @ScrewTSW @axel7083  ?

**Comment by cbr7** [comment]
@odockal about windows I don't know what more I can do, I've managed to isolate where the freeze is located, but at this point investigating further is beyond my capabilities, as for mac, once it's merged I can look into it as part of the other task that stabilizes e2e tests on macOS that I have.

**Comment by odockal** [comment]
@cbr7 Np. So what will happen when we encounter the problem on the first app to test and it takes full timeout of the test? Am I correct that since it is serial it wont try to run the rest of recipes? 

It would be nice that it wont spend resources if we know it wont be successful.

**Review by odockal — APPROVED** [review]

**Comment by cbr7** [comment]
@benoitf @jeffmaury can you please review if you have some free time

**Review by benoitf — APPROVED** [review]

**Review by axel7083 — APPROVED** [review]

**Pull request merged**
