### PR TITLE
Readme: remove references to yarn

### PR DESCRIPTION
**Pull request by maryamtahhan**
### What does this PR do?
Updates the Readme.md file to reference pnpm rather than yarn, cleans up some trailing spaces.

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
Thanks @maryamtahhan for taking the time to update the README! :rocket: 

> :warning: we have a requirement that the commits follow the Conventional Commits spec, you might need to change the commit name

**Comment by maryamtahhan** [comment]
I will update it

**Comment by benoitf** [comment]
adding reference to https://github.com/containers/podman-desktop-extension-ai-lab/issues/1898

**Comment by benoitf** [comment]
also not closing the referenced issue as it only fixed a subset

**Pull request merged**
