### PR TITLE
playground: add description when there's no playground

### PR DESCRIPTION
**Pull request by vrothberg**
### What does this PR do?
Based on user feedback, add the description from the dashboard to the playgrounds page when there is none running.  This way, new users receive more information and guidance and have an easier time navigating AI Lab and its functionality.

### Screenshot / video of UI
Screenshot 2024-04-11 at 11 44 06

### What issues does this PR fix or reference?

Fixes: #877

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
maybe also need to say really what it does like today:
- Generic chat client using the OpenAI API to interact with the model service
- you can still interact with API using the services (where you have details / snippets on how to do that)

**Comment by vrothberg** [comment]
Great idea, @benoitf ! Shall we add these details to the Dashboard as well?

**Comment by vrothberg** [comment]
@jeffmaury, how about the following?

---

Playground environments allow for experimenting with available models in a local environment. An intuitive user prompt helps in exploring the capabilities and accuracy of various models and aids in finding the best model for the use case at hand.

Once started, each playground ships with a generic chat client to interact with the model service. The Services [button] page allows for accessing running model services and provides further details and code snippets to interact with a service.

**Comment by slemeur** [comment]
Why wouldn't we claim compatibility with Open AI Apis?

**Comment by vrothberg** [comment]
Updated both, the Dashboard and the Playgrounds page:
Screenshot 2024-04-11 at 14 09 27
Screenshot 2024-04-11 at 14 09 31

**Comment by vrothberg** [comment]
I am cool either way: Open AI, well known Chat API, or as it is right now.

**Comment by vrothberg** [comment]
@jeffmaury @benoitf @slemeur, ready to get in?

**Review by benoitf — APPROVED** [review]

**Comment by vrothberg** [comment]
@feloy PTAL

**Review by feloy — APPROVED** [review]

**Pull request merged**
