### PR TITLE
feat: add warning banner to recipe page

### LINKED ISSUE #874: Warn users if they are using a podman machine with few resources; recipe

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR just have the code for adding the warning banner to the recipe page. It is based on https://github.com/containers/podman-desktop-extension-ai-lab/pull/856

### Screenshot / video of UI

warning_recipe_2

### What issues does this PR fix or reference?

it resolves #874 

### How to test this PR?

1. same as #856 but on the recipe page

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM, great work, @lstocchi !

Needs a rebase to resolve the merge conflicts.

**Review by jeffmaury — CHANGES_REQUESTED** [review]
After I started Podman Desktop, I try to create a recipe and it tells me that the Podman Machine is stopped and the status is never update even if my Podman Machine is started (checked from the CLI)

**Comment by lstocchi** [comment]
@jeffmaury ok, i'll merge this then. 
Can you please open an issue elaborating a bit more about your first concern? I didn't get it tbh.

For the podman machine should we open an issue as well to investigate more and tell it to the podman team? Or maybe @vrothberg have some more info about it

**Comment by vrothberg** [comment]
> For the podman machine should we open an issue as well to investigate more and tell it to the podman team? Or maybe @vrothberg have some more info about it

I think it's best to open an issue against Podman with a reproducer.

**Pull request merged**
