### PR TITLE
feature: adding stop button playground

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adding a Stop button to the playground when the LLM is responding. 

### Screenshot / video of UI

https://github.com/user-attachments/assets/f833fe0c-c175-4a7b-9df4-8b45a0022de6

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1089

### How to test this PR?

- [x] unit tests has been provided

**Manually**

- Create playground
- Submit message
- Stop message
- Again

### CODE REVIEW

**Comment by axel7083** [comment]
> Also, should we indicate somewhere that the response has been aborted ?

The server does not precise if it stop because the LLM provide a stop token or because he received a abort signal. We could incude this info in the Message interface from the client side, but I would rather not for now.

**Comment by ekidneyrh** [comment]
Yah we should have the buttons follow the same format as those on the details page

image

There's not a format decided upon for the outline / secondary version of it yet, but you could make two separate buttons side by side, one for send and one for stop?

**Comment by axel7083** [comment]
I updated the design and the screenshot to match the discussion we had in the UI call

**Review by benoitf — APPROVED** [review]
just wondering if the creation of the manager object should not be in the beforeEach method as it's a lot of copy paste everywhere and each we add a new parameter we need to change all tests methods

**Comment by axel7083** [comment]
> just wondering if the creation of the manager object should not be in the beforeEach method as it's a lot of copy paste everywhere and each we add a new parameter we need to change all tests methods

Yes, I rewrote those pretty old tests.

**Pull request merged**
