### PR TITLE
fix: model deletion

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

When trying to delete a model we faced "EPERM: operation not permitted". When the deletion start, it was blocking itself trying to delete the directory with the model in it. I was not able to find exactly why there was this problem, but deleting first the file, then the directory solved the issue.

> I suspect some kind of weird behaviour with the filesystem watcher and the rm retry/force arguments.

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/730

### How to test this PR?

- [x] unit tests cover the chage

**Please test manually**

#### Scenario 1

- (1) download a model
- (2) delete it

#### Scenario 2

- (1) download a model
- (2) start a recipe/model service
- (3) stop the model service/recipe
- (4) delete the mode

Please update the following after testing

- [x] Windows (Axel)
- [x] Mac (Philippe)
- [ ] Linux

### CODE REVIEW

**Comment by feloy** [comment]
Both scenarios work for me on mac

**Review by lstocchi — COMMENTED** [review]
I just tried on win but i still see this 
image

I open AI lab, go to summarizer ,select a model which i don't have on my machine, start the app, wait it started, stop it, try to delete the model.

**Comment by feloy** [comment]
> I just tried on win but i still see this image
> 
> I open AI lab, go to summarizer ,select a model which i don't have on my machine, start the app, wait it started, stop it, try to delete the model.

It seems there is an inconsistent behaviour: if I try to start a recipe with the **default** model not being on disk, I get an error saying that the model is not downloaded.

But I can do this with a non-default model, the model will be downloaded during the AI App start.

**Comment by axel7083** [comment]
> I just tried on win but i still see this image
> 
> I open AI lab, go to summarizer ,select a model which i don't have on my machine, start the app, wait it started, stop it, try to delete the model.

😢 do you have other file in your folder ? tmp ? can you ls ?

**Comment by lstocchi** [comment]
> @lstocchi do you have other file in your folder ? tmp ? can you ls ? 😢

I tried again after emptying the whole models folder to being sure i didn't have anything dirty. Still the same :(

**Comment by axel7083** [comment]
> > @lstocchi do you have other file in your folder ? tmp ? can you ls ? 😢
> 
> I tried again after emptying the whole models folder to being sure i didn't have anything dirty. Still the same :( BTW there is only the gguf file inside the folder

Managing files on windows is a nightmare, I'm tired of it. rmdir is after rm, rm is suppose to delete the file, then rmdir delete the folder. rmdir is not suppose to be call if rm fails. rm file seems to do some kind of magic trick where it consider the file is properly deleted when it is not, and the file is locked, and only on process exit, the file is deleted not before, only on exit....

@benoitf any idea ? I'm starting to get lost with this

**Comment by feloy** [comment]
I was reinstalling my windows machine today, I should be able to have a look on Tuesday. Files on Windows are a nightmare, I agree 🥵

**Comment by benoitf** [comment]
I would tend to say to always use `rm` which is the newer API.

That said, on Windows, most of the issue are around file locking. So before deleting we need to be sure that no process are reading the file, etc.

Are you able to list who is owning the lock on the file ?

In the past, I know that for some projects we used like some folders with timestamp to be sure like for example to not try to write again in a folder with a previous lock.

And then, a scheduler would perform cleanup asynchronously. Files/Folders are just unwatched/removed from their availability.

so when we delete we may not really delete immediately but schedule for deletion, but for sure we remove for a resource so the file are no longer being available

**Comment by axel7083** [comment]
Closing for now as I don't see easy solution

**Pull request closed without merging**
