### PR TITLE
chore: enable pre-commit

### PR DESCRIPTION
**Pull request by maryamtahhan**
### What does this PR do?

- Enables [pre-commit](https://pre-commit.com/) hook for the repo.
- Runs the pre-commit plugins on the files in the repo and applied the relevant changes.

### How to test this PR?

```bash
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

### CODE REVIEW

**Comment by axel7083** [comment]
Thanks @maryamtahhan, I do not think podman-desktop are familair with pre-commit, on podman-desktop repository we seems to be using husky, we also have an issue related to using it on ai-lab https://github.com/containers/podman-desktop-extension-ai-lab/issues/1633

**Comment by jeffmaury** [comment]
Thanks for your contribution. However, it requires Python which is too much. Podman Desktop uses Husky for such, would you mind going that direction ?

**Review by benoitf — COMMENTED** [review]
thanks for the contribution,

as the PR is doing lot of different things, I would encourage you to open small chunks before providing a full solution.

For example, file a PR fixing all the codespell issue

then, file an issue prompting if it's possible to enable some code spelling issues on the repository. Probably here I would recommend that it's ensured on the PR check / GitHub action because pre-commit hooks are great but people can bypass them

then, open a dedicated PR just removing trailing whitespaces or EOF, etc.

**Comment by maryamtahhan** [comment]
No problem - I can break down the issues the pre-commit hooks picked up into separate PRs (without the actual pre-commit hook itself)...

I will have a look at the husky route.

**Comment by benoitf** [comment]
also for the trailing spaces, EOF the repository is using prettier but maybe some files are ignored/skipped explaining why few files have problems

**Pull request closed without merging**
