### PR TITLE
fix: cannot delete the model with operation not permitted

### LINKED ISSUE #730: Cannot delete the model with operation not permitted
I had a chatbot app nice and working. I have stopped the app, deleted the model service and tried to delete the model.

deleting_model_operation_not_permitted

Error:
```
Error deleting model hf.TheBloke.mistral-7b-instruct-v0.1.Q4_K_M. Error: EPERM: operation not permitted, lstat 'C:\Users\Ondrej\podman-desktop\ai-studio\models\hf.TheBloke.mistral-7b-instruct-v0.1.Q4_K_M\mistral-7b-instruct-v0.1.Q4_K_M.gguf'
```

Error in the dev console:
```
VM5:2 main ↪️ [ai-studio] Something went wrong while getting file stats (probably in use). Error: EPERM: operation not permitted, stat 'C:\Users\Ondrej\podman-desktop\ai-studio\models\hf.TheBloke.mistral-7b-instruct-v0.1.Q4_K_M\mistral-7b-instruct-v0.1.Q4_K_M.gguf'
    at Object.stat (node:internal/fs/sync:58:25)
    at statSync (node:fs:1669:17)
    at t.statSync (node:electron/js2c/node_init:2:5052)
    at ModelsManager.getLocalModelsFromDisk (C:\Users\Ondrej\.local\share\containers\podman-desktop\plugins\ghcrioprojectatomicaistudio\dist\extension.js:10275:19)
    at ModelsManager.deleteLocalModel (C:\Users\Ondrej\.local\share\containers\podman-desktop\plugins\ghcrioprojectatomicaistudio\dist\extension.js:10327:14)
```

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #730

### What does this PR do?

Fixes error spawn when deleting a just downloaded model on Windows

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#730 

### How to test this PR?

1. Download a model
2. Once it is downloaded, delete it

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
What was the root of the issue ? I am not sure to follow why it fixes the problem to just move it inside the on callback ?

**Comment by jeffmaury** [comment]
> What was the root of the issue ? I am not sure to follow why it fixes the problem to just move it inside the on callback ?

The file was opened twice: the first time when the redirect response was received (we opened the file but to do use the handle so it stays open) and a second time after the redirection is processed. So at then end the second handle is closed but not the first one. The path delay the creation of the handle when it's really needed

**Comment by axel7083** [comment]
> > What was the root of the issue ? I am not sure to follow why it fixes the problem to just move it inside the on callback ?
> 
> The file was opened twice: the first time when the redirect response was received (we opened the file but to do use the handle so it stays open) and a second time after the redirection is processed. So at then end the second handle is closed but not the first one. The fix delay the creation of the handle when it's really needed

But, this is only valid for the `.tmp` file, as when the download is finish we rename it. The deletion issue was on the renamed file ?

**Comment by jeffmaury** [comment]
> > > What was the root of the issue ? I am not sure to follow why it fixes the problem to just move it inside the on callback ?
> > 
> > 
> > The file was opened twice: the first time when the redirect response was received (we opened the file but to do use the handle so it stays open) and a second time after the redirection is processed. So at then end the second handle is closed but not the first one. The fix delay the creation of the handle when it's really needed
> 
> But, this is only valid for the `.tmp` file, as when the download is finish we rename it. The deletion issue was on the renamed file ?

Yes but it fixes the issue so I think Windows is now smarter than it was and it moves the open handles to the renamed file

**Review by lstocchi — APPROVED** [review]
Tried to delete a model after having started/stopped a recipe and an inference server. Works fine 🚀

**Review by axel7083 — APPROVED** [review]

**Pull request merged**
