### PR TITLE
chore: light mode `Recipe details` page

### LINKED ISSUE #1286: chore: light mode `Recipe details` page

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #1286

### What does this PR do?

Light mode `Recipe details` page

### Screenshot / video of UI

image

image

### What issues does this PR fix or reference?

#1286

### CODE REVIEW

**Comment by benoitf** [comment]
I'm not sure about the colors of white text on top of a grey background for the contrast I expect to have maybe black color for the text ?

**Comment by lstocchi** [comment]
I used `text-[var(--pd-details-body-text)]` for the text in the details page in desktop, following https://github.com/containers/podman-desktop/wiki/Design-System-Theming#details-pages

**Review by axel7083 — APPROVED** [review]
LGTM

**Review by lstocchi — COMMENTED** [review]
Should this also be updated https://github.com/containers/podman-desktop-extension-ai-lab/pull/1317/files#diff-63cf42927bc970a48cf653baf0516d097db0c79ffe407ceee3f91d7ea545364bR109 ? 
To clean the charcoal background of the categories
image

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
