### PR TITLE
feat: revamp recipes list page

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Following one of the mockup in https://github.com/containers/podman-desktop-extension-ai-lab/issues/1126, improving the recipes card.

#### Notable change

- Adding an icon showing the status (cloned or not) similar to the one in extension catalog
- Adding the path in the card 

### Screenshot / video of UI

image

image

image

### What issues does this PR fix or reference?

Fixes partially https://github.com/containers/podman-desktop-extension-ai-lab/issues/1126

### How to test this PR?

- [x] unit tests has been provided

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
for the path inside the card I don't know if we should truncate the middle of the path so we see the beginning and the end of the path but it can also be a bad idea !

**Comment by axel7083** [comment]
> for the path inside the card I don't know if we should truncate the middle of the path so we see the beginning and the end of the path but it can also be a bad idea !

We will probably iterate a bit on this with Emma when she will be back ! I keep your remark in mind, I also feel a bit weird with the path.

**Comment by jeffmaury** [comment]
> for the path inside the card I don't know if we should truncate the middle of the path so we see the beginning and the end of the path but it can also be a bad idea !

Yes can't we have the full path as tooltip ?

**Review by jeffmaury — APPROVED** [review]
LGTM comment wise

**Comment by feloy** [comment]
I find the recipe status button/indicator disturbing. It's ok when the recipe is downloadable, but when it is downloaded, the button is still active and does nothing. Also, a tooltip would help understand the meaning

**Comment by axel7083** [comment]
⚠️ NOT INCLUDED IN THIS PR

I had a little fun with finding a nice way of allowing the user to see the full path, and I though: what if the text automatically scroll when hovering

https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/99d1eb8a-459e-4f64-b122-45385a131284

if this idea please some people, I could make another PR to include it, what do you think @jeffmaury @benoitf @deboer-tim

**Comment by jeffmaury** [comment]
> ⚠️ NOT INCLUDED IN THIS PR
> 
> I had a little fun with finding a nice way of allowing the user to see the full path, and I though: what if the text automatically scroll when hovering
> text-hover-scroll.mp4
> 
> if this idea please some people, I could make another PR to include it, what do you think @jeffmaury @benoitf @deboer-tim
> 
> > I can control the speed of the animation, I am also thinking we could add `cursor-copy` and make it copy when the user click on it

Seems to me that it is more common to have a UI glitch (tooltip) that shows the full path when a specific UI action is taken (hover,...). Here the con that I see is that the full path is not displayed entirely but that's still an improvement

**Comment by feloy** [comment]
> > ⚠️ NOT INCLUDED IN THIS PR
> > I had a little fun with finding a nice way of allowing the user to see the full path, and I though: what if the text automatically scroll when hovering
> > text-hover-scroll.mp4
> > if this idea please some people, I could make another PR to include it, what do you think @jeffmaury @benoitf @deboer-tim
> > > I can control the speed of the animation, I am also thinking we could add `cursor-copy` and make it copy when the user click on it
> 
> Seems to me that it is more common to have a UI glitch (tooltip) that shows the full path when a specific UI action is taken (hover,...). Here the con that I see is that the full path is not displayed entirely but that's still an improvement

Also, one important thing for the user I think is to be able to copy the path string. If the path is not displayed completely, the copy is not effective. The tooltip won't help either, as its content cannot be copied. Should we add a copy button?

**Comment by axel7083** [comment]
Merging for now this PR and I will open an issue for follow up

**Pull request merged**
