### PR TITLE
feat: implement pull model for API

### LINKED ISSUE #1583: Provide REST endpoint for downloading/pulling model

### PR DESCRIPTION
**Pull request by feloy**
### What does this PR do?

Adds a `/api/pull` endpoint to the API to download models

### Screenshot / video of UI

https://github.com/user-attachments/assets/bcc8fb65-cec6-4c79-b85d-6b55875d9f83

### What issues does this PR fix or reference?

Fixes #1583 

### How to test this PR?

Start AI Lab extension

```
$ OLLAMA_HOST=localhost:10434 ollama pull facebook/detr-resnet-101
// should download model
$ OLLAMA_HOST=localhost:10434 ollama pull facebook/detr-resnet-101
// should indicate success and not reload model
$ OLLAMA_HOST=localhost:10434 ollama pull unknown-model
// should fail with error message
```

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Seems to me that we are always working in streaming mode ?

**Comment by feloy** [comment]
> Seems to me that we are always working in streaming mode ?

You mean that all responses of the `/api/pull` are JSON streams in this implementation?

It also seems to be the case for ollama implementation, for example:

```
$ curl -X POST localhost:10343/api/pull -d '{"model": "unknown"}'
{"status":"pulling manifest"}
{"error":"pull model manifest: file does not exist"}
```

**Review by jeffmaury — APPROVED** [review]
LGTM

Only remark is that I found it strange that 200 is returned in case of error in non streaming mode

**Comment by feloy** [comment]
> LGTM
> 
> Only remark is that I found it strange that 200 is returned in case of error in non streaming mode

Where? I can only see 500 codes when returning errors, in non-streaming mode

**Comment by jeffmaury** [comment]
> > LGTM
> > Only remark is that I found it strange that 200 is returned in case of error in non streaming mode
> 
> Where? I can only see 500 codes when returning errors, in non-streaming mode

Sorry that was in streaming mode

**Review by gastoner — APPROVED** [review]
Works well

**Pull request merged**
