### PR TITLE
feature: adding versioning to the catalog

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

This PR set a version to the catalog, current `1.0`. When undefined or different, the user-catalog will not be loaded and a warning will be logged.

To ensure the user-catalog respect the format, the `CatalogUtils` file has been created, which will properly check for all the fields.

### Screenshot / video of UI

https://github.com/user-attachments/assets/744cc19d-bbea-4b46-a814-1da62b540684

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/59

### How to test this PR?

- [x] unit tests has been provided

Reproduce video above

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
Any reason why we do not show any warning to the user so that it is visible without opening the console?

**Comment by axel7083** [comment]
> Any reason why we do not show any warning to the user so that it is visible without opening the console?

We could @lstocchi. This is not the goal of this PR, I can open a follow up issue

**Review by jeffmaury — APPROVED** [review]
LGTM. I'm wondering if we should not issue a notification or report on UI that user catalog is invalid

**Comment by axel7083** [comment]
> LGTM. I'm wondering if we should not issue a notification or report on UI that user catalog is invalid

Same remark as Luca, I will open an issue and add it to the backlog

**Comment by axel7083** [comment]
Opened https://github.com/containers/podman-desktop-extension-ai-lab/issues/1394

**Review by lstocchi — APPROVED** [review]

**Pull request merged**
