### PR TITLE
feat: add dashboard banner

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adding the illustration made by @ekidneyrh to the dashboard.

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/905

### How to test this PR?

Open dashboard page

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Wondering PNG vs SVG ?

**Comment by axel7083** [comment]
> Wondering PNG vs SVG ?

The svg provided has a lot a properties related to the tool used, therefore the png was a better alternative as it does not come with all of this metadata

image

**Comment by benoitf** [comment]
usually we cleanup metadata ( you can drop them with tools or manually etc)  but I would go with svg

**Comment by benoitf** [comment]
I would define it as a svelte component as well

**Review by vrothberg — COMMENTED** [review]
Not a review but a compliment to the team:  the dashboard looks really great!

**Comment by axel7083** [comment]
@benoitf @jeffmaury  I created a svelte component for the svg after removing the meta data

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by lstocchi — APPROVED** [review]
LGTM 🚀

**Pull request merged**
