### PR TITLE
feat: add function calling recipe to the catalog

### LINKED ISSUE #1831: Add function calling recipe to the catalog
### Is your enhancement related to a problem? Please describe

The new recipe should be added

### Describe the solution you'd like

Update the catalog

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #1831

### What does this PR do?

Add the function calling recipe to the catalog

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

#1831 

### How to test this PR?

Start the function calling recipe

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by gastoner — APPROVED** [review]
LGTM, I expect that the "version" will be changed from `ref` to `1.3`after merge?

**Review by axel7083 — APPROVED** [review]
LGTM, I still wonder if we should try to enhance the UX of the recipe based on the feedback got in the UX call?

**Comment by jeffmaury** [comment]
> LGTM, I expect that the "version" will be changed from `ref` to `1.1.3`after merge?

Yes if AI Recipes team can tag a release before we release Podman AI Lab

**Comment by jeffmaury** [comment]
> LGTM, I still wonder if we should try to enhance the UX of the recipe based on the feedback got in the UX call?

Yes in a follow up PR

**Pull request merged**
