### PR TITLE
feat(models): polish models table

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Change the row columns of the Model table for better readability

#### Models page

**before**

image

**after**

image

#### Recipe models tab

**before**

image

**after**

image

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/701

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
I really love the new UI, thanks!  It's much easier to browse the models now.

One thing we may improve later on is the CREATION column.  Other interfaces call it AGE which I find more intuitive to understand.  Can we change the name?

**Comment by axel7083** [comment]
> I really love the new UI, thanks! It's much easier to browse the models now.
> 
> One thing we may improve later on is the CREATION column. Other interfaces call it AGE which I find more intuitive to understand. Can we change the name?

I like age, let's use that !

**Comment by axel7083** [comment]
@vrothberg I've updated the screenshots

**Review by vrothberg — APPROVED** [review]
Nice, thank you!

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
