### PR TITLE
fix: provide icon for playgrounds

### LINKED ISSUE #527: Design Icons for Playground Environments
This is a design issue for the creation of the Playground Icons in AI Studio

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #527

### What does this PR do?

Add new icon for playground

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

#527 

### How to test this PR?

Go to the playgrounds page

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
Should we also update the icon on the left sidebar?

**Comment by slemeur** [comment]
> Should we also update the icon on the left sidebar?
Yeah I think it would be best for consistency

**Comment by axel7083** [comment]
The size does seems not match the one in the models, container etc.

**Review by vrothberg — COMMENTED** [review]
I am bit puzzled about this change.

Looking at the screenshot below, the Services page looks quite different as it allows for selecting and deleting selected services. Managing the different objects and the workflows don't feel consistent at the moment:
Screenshot 2024-04-17 at 17 46 24

One thing that struck my eyes is that the icon isn't centered between the name of the playground and the left border:

Screenshot 2024-04-17 at 17 46 26

**Comment by jeffmaury** [comment]
> I am bit puzzled about this change.
> 
> Looking at the screenshot below, the Services page looks quite different as it allows for selecting and deleting selected services. Managing the different objects and the workflows don't feel consistent at the moment: Screenshot 2024-04-17 at 17 46 24
> 
> One thing that struck my eyes is that the icon isn't centered between the name of the playground and the left border:
> 
> Screenshot 2024-04-17 at 17 46 26

I think that's a virtual glitch because of the lowercase characters. Current table implementation does not support vertical alignment

**Comment by vrothberg** [comment]
Feel free to merge at will.  It's not a blocker for me.

**Comment by slemeur** [comment]
LGTM

**Review by slemeur — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]

**Pull request merged**
