### PR TITLE
feat: added lmstudio-comunity granite3 gguf model

### LINKED ISSUE #1962: Add Granite 3.0 to the models list
### Is your enhancement related to a problem? Please describe

https://huggingface.co/ibm-granite/granite-3.0-8b-instruct are now available

### Describe the solution you'd like

We should make the new Granite 3.0 models available within AI Lab.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Adds lmstudio-comunity granite3 gguf model (https://huggingface.co/lmstudio-community/granite-3.0-8b-instruct-GGUF)

Uses lmstudio-comunity granite3 instead of "official" ibm-granite, because IBM did not created gguf version so far 

### What issues does this PR fix or reference?
Closes #1962 

### How to test this PR?
Assert that granite3 model is in ai-lab

### CODE REVIEW

**Comment by feloy** [comment]
It is difficult to see in the patch what are the changes and what is part of the reformatting. Could you please create 2 distinct commits?

**Comment by axel7083** [comment]
cc @slemeur the added model is the following https://huggingface.co/lmstudio-community/granite-3.0-8b-instruct-GGUF could you confirm?

**Comment by jeffmaury** [comment]
> cc @slemeur the added model is the following https://huggingface.co/lmstudio-community/granite-3.0-8b-instruct-GGUF could you confirm?

https://huggingface.co/ibm-granite?search_models=gguf

**Comment by axel7083** [comment]
> https://huggingface.co/ibm-granite?search_models=gguf

They do not have the gguf for 3.0 https://huggingface.co/collections/ibm-granite/granite-30-language-models-66fdb59bbb54785c3512114f

**Comment by gastoner** [comment]
> It is difficult to see in the patch what are the changes and what is part of the reformatting. Could you please create 2 distinct commits?

The model is just "{
      "id": "hf.lmstudio-community.granite-3.0-8b-instruct-GGUF",
      "name": "lmstudio-community/granite-3.0-8b-instruct-GGUF",
      "description": "image/png\n\n# lmstudio-community/granite-3.0-8b-instruct\nThis is the Q4_K_M converted version of the original [`ibm-granite/granite-3.0-8b-instruct`](https://huggingface.co/ibm-granite/granite-3.0-8b-instruct).\nRefer to the [original model card](https://huggingface.co/ibm-granite/granite-3.0-8b-instruct) for more details.",
      "registry": "Hugging Face",
      "license": "Apache-2.0",
      "url": "https://huggingface.co/lmstudio-community/granite-3.0-8b-instruct-GGUF/resolve/main/granite-3.0-8b-instruct-Q4_K_M.gguf",
      "memory": 4942856128,
      "sha256": "bb32555f5a0bfa077aa2bfb17d43b7f76d372e7e57d433999592dc32d5310ab8",
      "backend": "llama-cpp"
    }," 
    
Everything else is formating

**Review by axel7083 — APPROVED** [review]

**Comment by feloy** [comment]
@gastoner 
Do you want to set it as recommended for some recipes? I remember it was set in the previous commit, but not here

**Comment by feloy** [comment]
@gastoner Do we want to set the model as recommended for some recipes?

**Comment by gastoner** [comment]
@feloy added the model to some recommendations

**Review by feloy — APPROVED** [review]

**Pull request merged**
