### PR TITLE
chore: update to the latest UI components

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
bump the library (including the tsconfig.json file) that will fix a compiler issue

### CODE REVIEW

**Comment by axel7083** [comment]
Need to update the pnpm-lock file

**Comment by benoitf** [comment]
yes I saw that
and I need to sign my commit 🤦

**Comment by benoitf** [comment]
so, need to fix something in AI lab as well first

**Review by deboer-tim — APPROVED** [review]
Identical to change I also did in bootc, LGTM.

**Review by gastoner — APPROVED** [review]

**Comment by benoitf** [comment]
closing over https://github.com/containers/podman-desktop-extension-ai-lab/pull/1995

**Pull request closed without merging**
