### PR TITLE
chore: improve resource disposal

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Improve the `studio.ts` file, to improve the way we dispose resources (managers).

Moreover, making more classes implements the disposable, to improve consistency in our designs 

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1166

### How to test this PR?

- [x] Unit tests has been provided

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
The way is is implemented is incompatible with the future REST server (see 
#822)
Why lazy initialization is not handled by the component itself when a request is processed (ie modelManager when getModels and so on is called)

**Comment by axel7083** [comment]
> Why lazy initialization is not handled by the component itself when a request is processed (ie modelManager when getModels and so on is called)

It can be, it would not be hard to change in the future, this PR is also cleanup, and documentation. We can make the change later for https://github.com/containers/podman-desktop-extension-ai-lab/issues/822

**Comment by jeffmaury** [comment]
> > Why lazy initialization is not handled by the component itself when a request is processed (ie modelManager when getModels and so on is called)
> 
> It can be, it would not be hard to change in the future, this PR is also cleanup, and documentation. We can make the change later for #822
> 
> Moreover, as for now, we avoid duplicating a lot of code inside each component, because if we want each of them to be initialized when used, with the _dynamic initialization_ you are talking about @jeffmaury they would all need to add some initialization check before each call (E.g. `if(!isInitiliazied()) init()`) ?

As we have the use case in the near future, I would prefer refactoring this PR now rather than later

**Comment by axel7083** [comment]
> As we have the use case in the near future, I would prefer refactoring this PR now rather than later

Alright, I updated the title of the Pull request to reflect what it does

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
