### PR TITLE
fix: add audio_to_text and object_detection recipes to the catalog

### LINKED ISSUE #695: Check adding more of the sample application
Check work necessary to cover the other example app available in https://github.com/redhat-et/locallm

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #695

### What does this PR do?

Add 2 recipes to the catalog

Blocked by:
- [x] https://github.com/containers/ai-lab-recipes/issues/219
- [x] https://github.com/containers/ai-lab-recipes/issues/220

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#695 

### How to test this PR?

Start the 2 new recipes:
-  for the object_detection recipe, you can use this image: http://images.cocodataset.org/val2017/000000039769.jpg
- for the audio_to_text you can use the jfk.wav that is located in the data folder of the recipe repository

### CODE REVIEW

**Comment by vrothberg** [comment]
I do not see new recipes in the catalog. Am I missing something?

Screenshot 2024-04-17 at 09 34 24

**Comment by lstocchi** [comment]
> I do not see new recipes in the catalog. Am I missing something?

Be sure that you're actually using this PR. I'm running it now and i can see them. Maybe you forgot to build after switching branch?

**Comment by vrothberg** [comment]
I verified to be using the right branch and ran `yarn install` and `yarn build` before the `yarn watch` but do not see the recipe.  Really strange.

**Review by vrothberg — APPROVED** [review]
Tested successfully 🏁  Great work!

**Review by axel7083 — COMMENTED** [review]
> aaaah ... I had to `rm -rf ~/.local/share/containers/podman-desktop` for it to show up.

I want to raise an important issue (again) justifying why you had to delete the folder, because on my computer too the new recipes was not visible

image

As I mentionned in https://github.com/containers/podman-desktop-extension-ai-lab/pull/771#discussion_r1549667567 and available in https://github.com/containers/podman-desktop-extension-ai-lab/issues/792

If the user at some point imported manually a model, which is the expected behaviour, he will not see new recipes after an update.

Because we have a unique catalog for the models and recipes, and we do not make any difference between user's one vs native. We ended up with a situation where the new recipes you added was not visible in my catalog because I have a copy of an old one.

**Comment by vrothberg** [comment]
I used the one from the local clone as Jeff mentioned in the PR description:

> for the audio_to_text you can use the jfk.wav that is located in the data folder of the recipe repository

**Comment by vrothberg** [comment]
> I want to raise an important issue (again).

@axel7083 that's what I must have hit as well.

**Review by axel7083 — COMMENTED** [review]
image

image

Images in markdown are not showing up

**Review by lstocchi — APPROVED** [review]
After reading the doc where it explains that we must use a 16-bit WAV file i was able to create a custom audio file and use it on the app. Maybe we should add this inside the app itself.
Like `Upload an audio file you wish to have translated (it only supports a 16-bit WAV files)`

BTW works fine. Just the problem with the images Axel mentioned.

**Comment by jeffmaury** [comment]
> Facing this issue on the audio to text. Which audio sample file did you use? I downloaded a youtube video as WAV and used it
> 
> image

In the data folder of the recipe repository (see PR description)

**Comment by jeffmaury** [comment]
> image
> 
> image
> 
> Images in markdown are not showing up

Will be addressed in a follow up PR when we will integrate recipes 1.0 as readme have changed on this side

**Comment by axel7083** [comment]
> After reading the doc where it explains that we must use a 16-bit WAV file i was able to create a custom audio file and use it on the app. Maybe we should add this inside the app itself. Like `Upload an audio file you wish to have translated (it only supports a 16-bit WAV files)`
> 
> BTW works fine. Just the problem with the images Axel mentioned.

I opened https://github.com/containers/ai-lab-recipes/issues/280 as this could be easy fixed by the application converting any audio to the expected format

**Pull request merged**
