### PR TITLE
chore: better start telemetry

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Including the `extension version` for the start event. (e.g. 0.4.0) and the `podman desktop version`.

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
hello, I'm not sure we need this

api is already sending version/name of the extension
https://github.com/containers/podman-desktop/blob/006e65bfb6f5191b184f47a82b83773c2e1f4ead/packages/main/src/plugin/telemetry/telemetry.ts#L415-L416

and the first event being sent include podman desktop version with operating system, etc

**Comment by axel7083** [comment]
> hello, I'm not sure we need this
> 
> api is already sending version/name of the extension https://github.com/containers/podman-desktop/blob/006e65bfb6f5191b184f47a82b83773c2e1f4ead/packages/main/src/plugin/telemetry/telemetry.ts#L415-L416
> 
> and the first event being sent include podman desktop version with operating system, etc

Oh very good to know, do we have access to the podman desktop version also ?

**Comment by benoitf** [comment]
yes
https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/telemetry/telemetry.ts#L354-L369

**Comment by axel7083** [comment]
Thanks for your time and precision, closing as not necessary

**Pull request closed without merging**
