### PR TITLE
fix: update Podman AI Lab logo

### LINKED ISSUE #1660: Update AI Lab logo and icon with new version
### Is your enhancement related to a problem? Please describe

The Podman Desktop AI Lab logo has been slightly reworked in https://github.com/containers/podman-desktop-internal/issues/308 and needs to be updated in the app.

### Describe the solution you'd like

The files are stored here: https://github.com/containers/podman-desktop-internal/tree/main/ai-lab/logo/new%20logo

**The icon**
The icon appears on the Podman Desktop left-hand navigation. 
[Light scheme](https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/svg/ai-lab-icon-light-scheme.svg) | [dark scheme](https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/svg/ai-lab-icon-dark-scheme.svg)

image

**The logo**
I would also suggest updating the Brain icon on the top: 
Screenshot 2024-09-04 at 14 16 28

### Describe alternatives you've considered

_No response_

### Additional context

We can discuss other placements in the comments.

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #1660

### What does this PR do?

Update Podman AI Lab logo

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

N/A

### How to test this PR?

Launch Podman AI Lab and check the icon in the left bar

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
resolution is much more smaller, expected ?

**Comment by jeffmaury** [comment]
> resolution is much more smaller, expected ?

@MariaLeonova can you clarify ?

**Comment by MariaLeonova** [comment]
> resolution is much more smaller, expected ?

@benoitf resolution of what is much smaller, please? I can make it any size that's needed and the svg files are available [here](https://github.com/containers/podman-desktop-internal/tree/main/ai-lab/logo/new%20logo/svg).

@jeffmaury it looks like the light version was used in the screenshot you provided, here's the dark scheme icon file:

https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/svg/ai-lab-icon-dark-scheme.svg

**Comment by jeffmaury** [comment]
We are using PNG format

**Review by benoitf — COMMENTED** [review]
before the image was W: 621px | H: 621px
now: 100px/97px

so it's not a square anymore (I would expect to be 100x100 or 97x97) and the size has been reduced by 6 in width

**Comment by MariaLeonova** [comment]
> before the image was W: 621px | H: 621px now: 100px/97px
> 
> so it's not a square anymore (I would expect to be 100x100 or 97x97) and the size has been reduced by 6 in width

It was 621x612 px for the icon on the left? That seems a bit much, but certainly can be done! I'll update it to be square.

**Comment by jeffmaury** [comment]
> Alright - these should be square, big and on a transparent background. Dark is for dark scheme, light is for light.
> 
> ai-lab-icon-dark-big ai-lab-icon-light-big

Can we get them in the internal repo ?

**Comment by MariaLeonova** [comment]
@jeffmaury of course! For next time it would be helpful for me to know from the start the exact requirements regarding size, format and where should the files be stored, so that I can prepare them the right way. 

https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/png/ai-lab-icon-light-big.png
https://github.com/containers/podman-desktop-internal/blob/main/ai-lab/logo/new%20logo/png/ai-lab-icon-dark-big.png

**Review by gastoner — APPROVED** [review]

**Review by axel7083 — APPROVED** [review]
We are going from 621x621 to 970x970 and adding 61KB to the image if this is okey then go

**Comment by ekidneyrh** [comment]
I know this is closed but should the brain logo be replaced too? 

Image

**Pull request merged**
