### PR TITLE
feat: add open recipe button

### LINKED ISSUE #688: AI Apps don't navigate back to the recipe
At the present, there is no easy way to get back to the recipe when looking at currently running AI Apps. This step is part of the desired e2e experience and aids in restarting the App with another model.

Screenshot 2024-03-26 at 10 22 41

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR adds the open recipe button that allows to being reidrected to the recipe page from the AI apps table.

As we already had 3 actions i needed to add the DropDownMenu component.
The DropDownMenu, DropDownMenuItem, DropDownMenuItems, and FlatMenu have been copied/pasted from Desktop. We definetely have to add them to the ui package and import it when we ends this rush.

### Screenshot / video of UI

open_recipe_2

### What issues does this PR fix or reference?

it resolves #688 

### How to test this PR?

1. run an AI app, go to the ai apps table and click on the kebab menu, then open recipe

### CODE REVIEW

**Comment by lstocchi** [comment]
> Just wondering if we should not favor open application as it's now hidden by default ?

Not sure to get it. You want to replace the restart action with the open ai app? and move the open app to the kebab menu?

**Comment by jeffmaury** [comment]
> > Just wondering if we should not favor open application as it's now hidden by default ?
> 
> Not sure to get it. You want to replace the restart action with the open ai app? and move the restart app to the kebab menu?

Yes that would be my proposition

**Comment by lstocchi** [comment]
> > > Just wondering if we should not favor open application as it's now hidden by default ?
> > 
> > 
> > Not sure to get it. You want to replace the restart action with the open ai app? and move the restart app to the kebab menu?
> 
> Yes that would be my proposition

Done and rebased. Gif in first post updated

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
