### PR TITLE
feat(model-services): making row selectable

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

- Making the rows in the Model Services page selectable
- Adding delete action for selected items

### Screenshot / video of UI

https://github.com/projectatomic/ai-studio/assets/42176370/776e5183-b2a1-4b65-acaf-68ceef9b7e10

### What issues does this PR fix or reference?

Fixes https://github.com/projectatomic/ai-studio/issues/699

### How to test this PR?

- [x] unit tests cover the new feature

### CODE REVIEW

**Comment by deboer-tim** [comment]
nit: you might want to add padding or tweak the title bar slightly, I notice the height is changing and causing the whole page to shift one pixel vertically when the button appears or disappears.

**Comment by axel7083** [comment]
> nit: you might want to add padding or tweak the title bar slightly, I notice the height is changing and causing the whole page to shift one pixel vertically when the button appears or disappears.

Thanks for noticing, it will be fixed by https://github.com/projectatomic/ai-studio/pull/692

**Review by lstocchi — COMMENTED** [review]
I think it is missing an inprogress prop as when i click on delete i don't understand if it's actually doing something

**Comment by axel7083** [comment]
> I think it is missing an inprogress prop as when i click on delete i don't understand if it's actually doing something

Not related to this PR, same as deleting a service using the delete button in the action column. There is an issue for that https://github.com/projectatomic/ai-studio/issues/547

**Review by feloy — APPROVED** [review]

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
