### PR TITLE
fix: provide icon for the extension

### LINKED ISSUE #875: Icon for AI Lab extension
Splitting the work for AI Lab dedicated extension icon
https://github.com/containers/podman-desktop-extension-ai-lab/issues/784

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #875

### What does this PR do?

Changes the icon for the extension

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

#875

### How to test this PR?

Launch Podman Desktop

### CODE REVIEW

**Comment by jeffmaury** [comment]
> I think it looks fine!

Then transforming to non draft PR then

**Review by ekidneyrh — APPROVED** [review]
LGTM :) Thanks Jeff

**Review by benoitf — COMMENTED** [review]
I think the image being added should be a square one 621px x 621px (then it should be centered properly inside the image)

**Comment by ekidneyrh** [comment]
AI-lab-logo-full-colour

**Review by benoitf — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]

**Pull request merged**
