### PR TITLE
feat: adding @podman-desktop/ui-svelte

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adding the `@podman-desktop/ui-svelte` library using `1.10.3`.

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1165

### CODE REVIEW

**Comment by benoitf** [comment]
I think there is a missing entry in tailwind.config.js to scan svelte and css files from the`@podman-desktop/ui-svelte`  in node_modules/

also maybe need to introduce it after 0.2.0 tag

**Review by benoitf — CHANGES_REQUESTED** [review]
it's a good time to introduce it

but it needs two things IMHO
- [x] requires a bump in the version as there was an issue in previous builds
- [x] addition into the tailwind config file like https://github.com/containers/podman-desktop-extension-bootc/blob/main/packages/frontend/tailwind.config.cjs#L26

**Comment by benoitf** [comment]
converting to draft as not updated

**Comment by axel7083** [comment]
cc @benoitf

**Review by benoitf — APPROVED** [review]

**Pull request merged**
