### PR TITLE
chore: fix trailing whitespace + EOL issues

### PR DESCRIPTION
**Pull request by maryamtahhan**
### What does this PR do?

- Fixes files that are missing a new line at the end.
- Fixes files that had too many new lines at the end.
- Fixes trailing whitespaces

### CODE REVIEW

**Comment by benoitf** [comment]
as reported in previous PR, please keep the template with all sections as it is in https://raw.githubusercontent.com/containers/podman-desktop-extension-ai-lab/refs/heads/main/.github/PULL_REQUEST_TEMPLATE.md

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by maryamtahhan** [comment]
I will rebase it now - sorry

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
